# Generated by Django 4.2.5 on 2023-10-28 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='s_id',
        ),
    ]
