# Generated by Django 4.2.5 on 2023-10-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_student_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_age',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Enter Student Age'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_email',
            field=models.EmailField(max_length=254, verbose_name='Enter Student Email '),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_gender',
            field=models.CharField(max_length=20, verbose_name='Select Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_name',
            field=models.CharField(max_length=100, verbose_name='Enter the Student Name'),
        ),
    ]
