# Generated by Django 4.2.5 on 2023-10-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_student_s_age_alter_student_s_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_age',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_name',
            field=models.CharField(max_length=100),
        ),
    ]
